SELECT CONCAT('/home/grep/src/', a.BOARD_ID, '/', b.FILE_ID, b.FILE_NAME, b.FILE_EXT) FILE_PATH
FROM USED_GOODS_BOARD a join USED_GOODS_FILE b
ON a.BOARD_ID = b.BOARD_ID
WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY FILE_ID DESC