SELECT YEAR(i.SALES_DATE) AS YEAR, MONTH(i.SALES_DATE) AS MONTH, u.GENDER, COUNT(DISTINCT(u.USER_ID)) AS USERS
FROM USER_INFO u
JOIN ONLINE_SALE i ON u.USER_ID = i.USER_ID
WHERE u.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER